### ISSUE TITLE
Demo Issue 

### ISSUE THREAD

**Issue by wrannaman** [alexvcasillas/react-onboarding#2]
Hey, 

Great work! Went to go check out the demo at https://onboarding-demo.reactive-labs.com/ and saw it was down. Just an fyi in case you didn't know.

**Comment by alexvcasillas** [comment]
Hey,

Thanks for the feedback, I forgot to redeploy the demo when made some changes at server 🤦🏻‍♂️

**Comment by wrannaman** [comment]
Haha, been there!
